---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-rag-config
data:
  API_BASE_URL: "https://backendlicitaciones.activeit.com"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  PORT: "5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: mp-rag-secrets
type: Opaque
data:
  OPENAI_API_KEY: "c2stcHJvai1tRmtmYUZFaXFoT3BwdXJGSnNROGhSZHJWSWltTjltcTJJRVhNa2JubGZKMUFITWswVjVQS01DUlpfczRCTlBoLUdqX3JFcFlxeFQzQmxia0ZKckFzcVM3UmFVZFYyc21wWFQyaVFqbWhMUkF1TXhyb1RzQVpMSURZV0UwQ203RHg4dGZSalpSa2tEUk4tYU1Md2ZzRVF4N3dlNEE="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-rag-deployment
  labels:
    app: mp-rag
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mp-rag
  template:
    metadata:
      labels:
        app: mp-rag
      annotations:
        kubectl.kubernetes.io/restartedAt: "{{ timestamp }}"
    spec:
      containers:
      - name: mp-rag
        image: docker.io/mpulgarf/mercadopublico-mp-rag:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mp-rag-config
        - secretRef:
            name: mp-rag-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mp-rag-service
spec:
  type: LoadBalancer
  selector:
    app: mp-rag 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000